- name: reboot
  shell: echo {{ inventory_hostname }} | reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: Warten bis Server neu gestartet ist
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
